services:
  # Database Service
  db:
    image: postgres:15-alpine
    container_name: dpl_db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend Service
  backend:
    image: yashsarvaiya2002/dpl-backend:latest
    container_name: dpl_backend
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8000"
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles

  # Frontend Service
  frontend:
    image: yashsarvaiya2002/dpl-frontend:latest
    container_name: dpl_frontend
    restart: always
    env_file: .env
    ports:
      - "3031:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
  media:
  staticfiles:
